### ISSUE TITLE
Rubygems is pointing to the wrong github repo

### ISSUE THREAD

**Issue by swebb** [christianvuerings/pikaday-gem#1]
https://rubygems.org/gems/pikaday-gem

The above page has the following links which all link to the old github repo. Could you please update them so they link to yours.

Homepage
Source Code
Documentation
Bug Tracker

**Comment by christianvuerings** [comment]
@swebb https://github.com/ets-berkeley-edu/pikaday-gem is actually the official repo. Also wanted to let you know that our version is deprecated and will no longer be maintained. We're now using the npm versions.
